### ISSUE TITLE
error in evaluation

### ISSUE THREAD

**Issue by gsanroma** [zubata88/mdgru#26]
When running the train+test experiment as described in 
https://zubata88.github.io/mdgru/how_to_use.html#train-test
the code ran into the an error, apparently during evaluation phase.
Find the details below. I also attach the log file.
[log.txt](https://github.com/zubata88/mdgru/files/3146521/log.txt)

```
INFO:eval:it: 2499, time: [i/o: 0.004388, processing: 4.636132, all: 4.64052], loss: 6.305851275101304e-05
INFO:eval:it: 2500, time: [i/o: 0.002093, processing: 4.635756, all: 4.637849], loss: 0.0106213837862$1477
INFO:eval:evaluating file /home/sanromag/DATA/WMH/mdgru/data/val/5183c7e2 of shape (176, 256, 256) wi$h w [64, 64, 64] and p [5, 5, 5]
Traceback (most recent call last):
  File "RUN_mdgru.py", line 122, in <module>
    run_mdgru()
  File "RUN_mdgru.py", line 118, in run_mdgru
    return runner.run()
  File "/home/sanromag/WORK/CODE/external/mdgru/mdgru/runner.py", line 423, in run
    self.train()
  File "/home/sanromag/WORK/CODE/external/mdgru/mdgru/runner.py", line 321, in train
    error = self.validation(showIt=self.save_validation_results, name=it)
  File "/home/sanromag/WORK/CODE/external/mdgru/mdgru/runner.py", line 221, in validation
    return_results=True)
File "/home/sanromag/WORK/CODE/external/mdgru/mdgru/eval/__init__.py", line 345, in test_all_available
    certainty[slicesa] *= np.arange(1.0 / (pp + 1), 1, 1.0 / (pp + 1)).reshape(reshapearr)
ValueError: cannot reshape array of size 6 into shape (5,1,1)
```

**Comment by gtancev** [comment]
I had the same error. It's due to this line:` np.arange(1.0 / (pp + 1), 1, 1.0 / (pp + 1))`
Should probably be `np.arange(1.0 / pp, 1, 1.0 / (pp + 1))`.
However, there is no problem if you use `-p [0 0 0]`
